name: CI
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  api:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: api } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with: { dotnet-version: 8.0.x }
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
      - run: dotnet test Api.Tests/Api.Tests.csproj --configuration Release --no-build --verbosity normal

  ui:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: ui } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci
      - run: npm run test -- --watch=false --browsers=ChromeHeadless
      - run: npm run build -- --configuration production
